"""RL-Kernel adapter boundary owned by vime."""

from vime.backends.rl_kernel_utils.adapter import (
    RLK_ALL_OPERATORS,
    RLK_OP_LINEAR_LOGP,
    RLK_OP_REFERENCE_LOGPROBS,
    RLK_OP_SELECTED_LOGPROBS,
    LinearLogpInputs,
    MockRlkOperatorAdapter,
    NoOpRlkOperatorAdapter,
    ReferenceScoreInputs,
    RlkCapability,
    RlkOperatorAdapter,
    RlkOperatorContract,
    RlkOperatorDecision,
    RlkOperatorResult,
    RlkOperatorTelemetry,
    RlkOperatorUnavailable,
    RlkPolicyContext,
    RlkRegistryOperatorAdapter,
    RlkRuntimeBatchMetadata,
    SelectedLogprobInputs,
    build_rlk_operator_adapter,
    linear_logp_inputs_from_vime,
    rlk_policy_context_from_args,
    runtime_batch_metadata_from_vime_batch,
)

__all__ = [
    "LinearLogpInputs",
    "MockRlkOperatorAdapter",
    "NoOpRlkOperatorAdapter",
    "ReferenceScoreInputs",
    "RLK_ALL_OPERATORS",
    "RLK_OP_LINEAR_LOGP",
    "RLK_OP_REFERENCE_LOGPROBS",
    "RLK_OP_SELECTED_LOGPROBS",
    "RlkCapability",
    "RlkOperatorContract",
    "RlkOperatorAdapter",
    "RlkOperatorDecision",
    "RlkOperatorResult",
    "RlkOperatorTelemetry",
    "RlkOperatorUnavailable",
    "RlkPolicyContext",
    "RlkRegistryOperatorAdapter",
    "RlkRuntimeBatchMetadata",
    "SelectedLogprobInputs",
    "build_rlk_operator_adapter",
    "linear_logp_inputs_from_vime",
    "rlk_policy_context_from_args",
    "runtime_batch_metadata_from_vime_batch",
]
